import requests


# Your API endpoint (adjust if running on a different port or domain)
API_URL = "http://127.0.0.1:8000/api/books_all/"

# List of 100 real book titles and authors
books = [
    {"title": "To Kill a Mockingbird", "author": "Harper Lee"},
    {"title": "1984", "author": "George Orwell"},
    {"title": "Pride and Prejudice", "author": "Jane Austen"},
    {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald"},
    {"title": "Moby-Dick", "author": "Herman Melville"},
    {"title": "War and Peace", "author": "Leo Tolstoy"},
    {"title": "The Catcher in the Rye", "author": "J.D. Salinger"},
    {"title": "The Hobbit", "author": "J.R.R. Tolkien"},
    {"title": "Brave New World", "author": "Aldous Huxley"},
    {"title": "The Odyssey", "author": "Homer"},
    {"title": "The Iliad", "author": "Homer"},
    {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky"},
    {"title": "Anna Karenina", "author": "Leo Tolstoy"},
    {"title": "Madame Bovary", "author": "Gustave Flaubert"},
    {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky"},
    {"title": "Les Misérables", "author": "Victor Hugo"},
    {"title": "The Divine Comedy", "author": "Dante Alighieri"},
    {"title": "Don Quixote", "author": "Miguel de Cervantes"},
    {"title": "Wuthering Heights", "author": "Emily Brontë"},
    {"title": "Jane Eyre", "author": "Charlotte Brontë"},
    {"title": "Great Expectations", "author": "Charles Dickens"},
    {"title": "David Copperfield", "author": "Charles Dickens"},
    {"title": "Bleak House", "author": "Charles Dickens"},
    {"title": "A Tale of Two Cities", "author": "Charles Dickens"},
    {"title": "The Picture of Dorian Gray", "author": "Oscar Wilde"},
    {"title": "Ulysses", "author": "James Joyce"},
    {"title": "Dubliners", "author": "James Joyce"},
    {"title": "A Portrait of the Artist as a Young Man", "author": "James Joyce"},
    {"title": "The Sound and the Fury", "author": "William Faulkner"},
    {"title": "Absalom, Absalom!", "author": "William Faulkner"},
    {"title": "Invisible Man", "author": "Ralph Ellison"},
    {"title": "Beloved", "author": "Toni Morrison"},
    {"title": "Song of Solomon", "author": "Toni Morrison"},
    {"title": "The Bluest Eye", "author": "Toni Morrison"},
    {"title": "Slaughterhouse-Five", "author": "Kurt Vonnegut"},
    {"title": "Cat's Cradle", "author": "Kurt Vonnegut"},
    {"title": "Breakfast of Champions", "author": "Kurt Vonnegut"},
    {"title": "Lolita", "author": "Vladimir Nabokov"},
    {"title": "Pale Fire", "author": "Vladimir Nabokov"},
    {"title": "Fahrenheit 451", "author": "Ray Bradbury"},
    {"title": "The Martian Chronicles", "author": "Ray Bradbury"},
    {"title": "Dune", "author": "Frank Herbert"},
    {"title": "Foundation", "author": "Isaac Asimov"},
    {"title": "I, Robot", "author": "Isaac Asimov"},
    {"title": "Neuromancer", "author": "William Gibson"},
    {"title": "Snow Crash", "author": "Neal Stephenson"},
    {"title": "Cryptonomicon", "author": "Neal Stephenson"},
    {"title": "The Left Hand of Darkness", "author": "Ursula K. Le Guin"},
    {"title": "A Wizard of Earthsea", "author": "Ursula K. Le Guin"},
    {"title": "The Dispossessed", "author": "Ursula K. Le Guin"},
    {"title": "The Road", "author": "Cormac McCarthy"},
    {"title": "Blood Meridian", "author": "Cormac McCarthy"},
    {"title": "No Country for Old Men", "author": "Cormac McCarthy"},
    {"title": "Gone with the Wind", "author": "Margaret Mitchell"},
    {"title": "The Grapes of Wrath", "author": "John Steinbeck"},
    {"title": "Of Mice and Men", "author": "John Steinbeck"},
    {"title": "East of Eden", "author": "John Steinbeck"},
    {"title": "On the Road", "author": "Jack Kerouac"},
    {"title": "The Dharma Bums", "author": "Jack Kerouac"},
    {"title": "Catch-22", "author": "Joseph Heller"},
    {"title": "Something Happened", "author": "Joseph Heller"},
    {"title": "Lord of the Flies", "author": "William Golding"},
    {"title": "The Spire", "author": "William Golding"},
    {"title": "A Clockwork Orange", "author": "Anthony Burgess"},
    {"title": "Earthly Powers", "author": "Anthony Burgess"},
    {"title": "Middlemarch", "author": "George Eliot"},
    {"title": "Silas Marner", "author": "George Eliot"},
    {"title": "Daniel Deronda", "author": "George Eliot"},
    {"title": "The Stranger", "author": "Albert Camus"},
    {"title": "The Plague", "author": "Albert Camus"},
    {"title": "The Myth of Sisyphus", "author": "Albert Camus"},
    {"title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez"},
    {"title": "Love in the Time of Cholera", "author": "Gabriel García Márquez"},
    {"title": "Chronicle of a Death Foretold", "author": "Gabriel García Márquez"},
    {"title": "The Old Man and the Sea", "author": "Ernest Hemingway"},
    {"title": "For Whom the Bell Tolls", "author": "Ernest Hemingway"},
    {"title": "The Sun Also Rises", "author": "Ernest Hemingway"},
    {"title": "A Farewell to Arms", "author": "Ernest Hemingway"},
    {"title": "The Call of the Wild", "author": "Jack London"},
    {"title": "White Fang", "author": "Jack London"},
    {"title": "Dracula", "author": "Bram Stoker"},
    {"title": "Frankenstein", "author": "Mary Shelley"},
    {"title": "The Time Machine", "author": "H.G. Wells"},
    {"title": "The War of the Worlds", "author": "H.G. Wells"},
    {"title": "The Invisible Man", "author": "H.G. Wells"},
    {"title": "Around the World in Eighty Days", "author": "Jules Verne"},
    {"title": "Journey to the Center of the Earth", "author": "Jules Verne"},
    {"title": "Twenty Thousand Leagues Under the Sea", "author": "Jules Verne"},
    {"title": "The Alchemist", "author": "Paulo Coelho"},
    {"title": "Veronika Decides to Die", "author": "Paulo Coelho"},
    {"title": "Eleven Minutes", "author": "Paulo Coelho"},
    {"title": "Life of Pi", "author": "Yann Martel"},
    {"title": "The Kite Runner", "author": "Khaled Hosseini"},
    {"title": "A Thousand Splendid Suns", "author": "Khaled Hosseini"},
    {"title": "And the Mountains Echoed", "author": "Khaled Hosseini"},
    {"title": "Memoirs of a Geisha", "author": "Arthur Golden"},
    {"title": "The Book Thief", "author": "Markus Zusak"},
    {"title": "The Shadow of the Wind", "author": "Carlos Ruiz Zafón"},
    {"title": "Angels & Demons", "author": "Dan Brown"},
    {"title": "The Da Vinci Code", "author": "Dan Brown"},
    {"title": "Inferno", "author": "Dan Brown"},
]

# Loop through and insert each book
for book in books:
    response = requests.post(API_URL, json=book)
    if response.status_code == 201:
        print(f"✅ Added: {book['title']} by {book['author']}")
    else:
        print(f"❌ Failed: {book['title']} ({response.status_code}) - {response.text}")
    print("Bulk insert completed.")